// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuctionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Replicas      []string               `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
	Amount        uint32                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionMessage) Reset() {
	*x = AuctionMessage{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionMessage) ProtoMessage() {}

func (x *AuctionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionMessage.ProtoReflect.Descriptor instead.
func (*AuctionMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuctionMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuctionMessage) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *AuctionMessage) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"t\n" +
	"\x0eAuctionMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\tR\breplicas\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\rR\x06amount2A\n" +
	"\x0eAuctionService\x12/\n" +
	"\aTraffic\x12\x0f.AuctionMessage\x1a\x0f.AuctionMessage(\x010\x012D\n" +
	"\x0fInternalService\x121\n" +
	"\tReplicate\x12\x0f.AuctionMessage\x1a\x0f.AuctionMessage(\x010\x01B\x14Z\x12Auction/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_proto_goTypes = []any{
	(*AuctionMessage)(nil), // 0: AuctionMessage
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: AuctionService.Traffic:input_type -> AuctionMessage
	0, // 1: InternalService.Replicate:input_type -> AuctionMessage
	0, // 2: AuctionService.Traffic:output_type -> AuctionMessage
	0, // 3: InternalService.Replicate:output_type -> AuctionMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
