// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BID_STATUS int32

const (
	BID_STATUS_BID_FAILED  BID_STATUS = 0
	BID_STATUS_BID_SUCCESS BID_STATUS = 1
	BID_STATUS_BID_TOO_LOW BID_STATUS = 2
)

// Enum value maps for BID_STATUS.
var (
	BID_STATUS_name = map[int32]string{
		0: "BID_FAILED",
		1: "BID_SUCCESS",
		2: "BID_TOO_LOW",
	}
	BID_STATUS_value = map[string]int32{
		"BID_FAILED":  0,
		"BID_SUCCESS": 1,
		"BID_TOO_LOW": 2,
	}
)

func (x BID_STATUS) Enum() *BID_STATUS {
	p := new(BID_STATUS)
	*p = x
	return p
}

func (x BID_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BID_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[0].Descriptor()
}

func (BID_STATUS) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[0]
}

func (x BID_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BID_STATUS.Descriptor instead.
func (BID_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

type T_Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bidder        string                 `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *T_Bid) Reset() {
	*x = T_Bid{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *T_Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T_Bid) ProtoMessage() {}

func (x *T_Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T_Bid.ProtoReflect.Descriptor instead.
func (*T_Bid) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *T_Bid) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *T_Bid) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type T_BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bidder        string                 `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Status        BID_STATUS             `protobuf:"varint,2,opt,name=status,proto3,enum=BID_STATUS" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *T_BidResponse) Reset() {
	*x = T_BidResponse{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *T_BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T_BidResponse) ProtoMessage() {}

func (x *T_BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T_BidResponse.ProtoReflect.Descriptor instead.
func (*T_BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *T_BidResponse) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *T_BidResponse) GetStatus() BID_STATUS {
	if x != nil {
		return x.Status
	}
	return BID_STATUS_BID_FAILED
}

type T_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBidder string                 `protobuf:"bytes,1,opt,name=highestBidder,proto3" json:"highestBidder,omitempty"`
	HighestBid    uint32                 `protobuf:"varint,2,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *T_Result) Reset() {
	*x = T_Result{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *T_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T_Result) ProtoMessage() {}

func (x *T_Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T_Result.ProtoReflect.Descriptor instead.
func (*T_Result) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *T_Result) GetHighestBidder() string {
	if x != nil {
		return x.HighestBidder
	}
	return ""
}

func (x *T_Result) GetHighestBid() uint32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

type T_StartAucReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuctionStart    int64                  `protobuf:"varint,1,opt,name=auctionStart,proto3" json:"auctionStart,omitempty"`       // In nanoseconds
	AuctionDuration int64                  `protobuf:"varint,2,opt,name=auctionDuration,proto3" json:"auctionDuration,omitempty"` // In nanoseconds
	Initiator       string                 `protobuf:"bytes,3,opt,name=initiator,proto3" json:"initiator,omitempty"`              // For debugging
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *T_StartAucReq) Reset() {
	*x = T_StartAucReq{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *T_StartAucReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T_StartAucReq) ProtoMessage() {}

func (x *T_StartAucReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T_StartAucReq.ProtoReflect.Descriptor instead.
func (*T_StartAucReq) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *T_StartAucReq) GetAuctionStart() int64 {
	if x != nil {
		return x.AuctionStart
	}
	return 0
}

func (x *T_StartAucReq) GetAuctionDuration() int64 {
	if x != nil {
		return x.AuctionDuration
	}
	return 0
}

func (x *T_StartAucReq) GetInitiator() string {
	if x != nil {
		return x.Initiator
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"7\n" +
	"\x05T_Bid\x12\x16\n" +
	"\x06bidder\x18\x01 \x01(\tR\x06bidder\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\"L\n" +
	"\rT_BidResponse\x12\x16\n" +
	"\x06bidder\x18\x01 \x01(\tR\x06bidder\x12#\n" +
	"\x06status\x18\x02 \x01(\x0e2\v.BID_STATUSR\x06status\"P\n" +
	"\bT_Result\x12$\n" +
	"\rhighestBidder\x18\x01 \x01(\tR\rhighestBidder\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x02 \x01(\rR\n" +
	"highestBid\"{\n" +
	"\rT_StartAucReq\x12\"\n" +
	"\fauctionStart\x18\x01 \x01(\x03R\fauctionStart\x12(\n" +
	"\x0fauctionDuration\x18\x02 \x01(\x03R\x0fauctionDuration\x12\x1c\n" +
	"\tinitiator\x18\x03 \x01(\tR\tinitiator\"\a\n" +
	"\x05Empty*>\n" +
	"\n" +
	"BID_STATUS\x12\x0e\n" +
	"\n" +
	"BID_FAILED\x10\x00\x12\x0f\n" +
	"\vBID_SUCCESS\x10\x01\x12\x0f\n" +
	"\vBID_TOO_LOW\x10\x022\xa4\x01\n" +
	"\x0eAuctionService\x12\x1d\n" +
	"\x03Bid\x12\x06.T_Bid\x1a\x0e.T_BidResponse\x12\"\n" +
	"\rGetHighestBid\x12\x06.Empty\x1a\t.T_Result\x12'\n" +
	"\x10BroadcastResults\x12\x06.Empty\x1a\t.T_Result0\x01\x12&\n" +
	"\fStartAuction\x12\x0e.T_StartAucReq\x1a\x06.EmptyB\x14Z\x12Auction/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_proto_goTypes = []any{
	(BID_STATUS)(0),       // 0: BID_STATUS
	(*T_Bid)(nil),         // 1: T_Bid
	(*T_BidResponse)(nil), // 2: T_BidResponse
	(*T_Result)(nil),      // 3: T_Result
	(*T_StartAucReq)(nil), // 4: T_StartAucReq
	(*Empty)(nil),         // 5: Empty
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: T_BidResponse.status:type_name -> BID_STATUS
	1, // 1: AuctionService.Bid:input_type -> T_Bid
	5, // 2: AuctionService.GetHighestBid:input_type -> Empty
	5, // 3: AuctionService.BroadcastResults:input_type -> Empty
	4, // 4: AuctionService.StartAuction:input_type -> T_StartAucReq
	2, // 5: AuctionService.Bid:output_type -> T_BidResponse
	3, // 6: AuctionService.GetHighestBid:output_type -> T_Result
	3, // 7: AuctionService.BroadcastResults:output_type -> T_Result
	5, // 8: AuctionService.StartAuction:output_type -> Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
